package com.elgin.study.spring.bean.lifecycle;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

/**
 * Bean 的生命周期
 *
 * invoke LifeCycleTestBean() construct method...
 * invoke setApplicationContext method...
 * invoke postProcessBeforeInitialization method.../invoke annotations with @PostConstruct method...
 * invoke afterPropertiesSet method...
 * invoke initMethod method...
 * invoke postProcessAfterInitialization method...
 * invoke annotations with @PreDestroy method...
 * invoke destory method...
 * invoke destoryMethod method...
 */
public class MainClass {

    public static void main(String[] args) {
        ApplicationContext ctx =new ClassPathXmlApplicationContext("lifeCycle/application.xml");
        LifeCycleTestBean bean=ctx.getBean(LifeCycleTestBean.class);
        //关闭容器
        ((ClassPathXmlApplicationContext) ctx).registerShutdownHook();

    }
}
